### ISSUE TITLE
VScom CAN-API could not be chosen

### ISSUE THREAD

**Issue by reymor** [reymor/novobusanalyzer#7]
When `RUSOKU TouCAN` was added the `VScom CAN-API` in `Driver Selection` cannot be chosen anymore.

![image](https://github.com/reymor/novobusanalyzer/assets/39070043/330f5148-efe4-4774-9d49-48803cd0f537)

**Comment by rusoku** [comment]
Increase driver select value in MainFrm.c file:
 ON_COMMAND_RANGE(IDC_SELECT_DRIVER,IDC_SELECT_DRIVER + 15, OnSelectDriver)
 ON_UPDATE_COMMAND_UI_RANGE(IDC_SELECT_DRIVER,IDC_SELECT_DRIVER + 15, OnUpdateSelectDriver)

**Comment by rusoku** [comment]
BTW: TouCAN adapter driver works ;-)

![novo_1](https://github.com/reymor/novobusanalyzer/assets/46974254/83226fc0-8d90-4abd-9712-debe6042ab1d)

**Comment by reymor** [comment]
I fix it.

Thanks @rusoku :)
